name: Compile Check

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore Dependencies
        run: dotnet restore CMSTool/FallGuys-CMSTool.csproj --runtime linux-x64

      - name: Build for Linux
        run: dotnet build CMSTool/FallGuys-CMSTool.csproj --runtime linux-x64 --configuration Release-Linux-x64 --no-restore

      - name: Test
        run: dotnet test CMSTool/FallGuys-CMSTool.csproj --runtime linux-x64 --no-build --verbosity normal

  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore Dependencies
        run: dotnet restore CMSTool/FallGuys-CMSTool.csproj --runtime win-x64

      - name: Build for Windows
        run: dotnet build CMSTool/FallGuys-CMSTool.csproj --runtime win-x64 --configuration Release-Win-x64 --no-restore

      - name: Test
        run: dotnet test CMSTool/FallGuys-CMSTool.csproj --runtime win-x64 --no-build --verbosity normal
